### ISSUE TITLE
Node Wont start

### ISSUE THREAD

**Issue by permabull** [mimblewimble/docs#12] opened 2019-01-17 09:43 UTC
Hi.

Ive followed the very simple guide to install the full node software.

But when I run grin nothing happens, any suggestions?

Its being installed becuase i created a wallet but later on it cant connect because nothing is running.

//Thanks B

**Comment by DanMarteens** [comment] 2019-01-19 20:41
Have the same problem, "grin" command execution doesn't take any output. Anyone solved it?

**Comment by sesam** [comment] 2019-01-21 10:53
Hi @RobertSundh ! This issue is in the wrong github - could you please close it? The best place for help building and running grin is start at the [troubleshooting page](https://github.com/mimblewimble/docs/wiki/Troubleshooting) and then come to the support chat: https://gitter.im/grin_community/support

**Comment by rw258906** [comment] 2019-01-22 22:31
I think that the problem is neither of you had rust installed.

**Comment by gits7r** [comment] 2019-01-28 21:51
Negative. I followed the exact instructions, installed latest rust and still grin server start does not do anything. No process is started. grin server config does indeed create a grin-server.toml file but regardless from where i run the grin server start command (path where grin-server.toml file is, or any other path) nothing happens. Something must be broken. And there's also no way to check node status, like grin server status that would indicate number of peers, progress, connectivity and so on. can't set a secondary host argument for my IPv6 address as well.

**Closed** 2020-09-28 20:33 UTC
